#!/usr/bin/env python3


import rospy
import moveit_commander
import moveit_msgs.msg
import sys
from std_msgs.msg import String
from std_msgs.msg import Float64
from geometry_msgs.msg import PoseStamped, Pose

class MotionPlanner():
    def __init__(self):
        moveit_commander.roscpp_initialize(sys.argv)
        rospy.init_node("try_rviz")
        manipulator = moveit_commander.MoveGroupCommander("manipulator")
        print(manipulator.get_end_effector_link())
        manipulator.allow_replanning(True)
        manipulator.set_goal_orientation_tolerance(0.2)
        #manipulator.set_planning_time(30)
        self.start_pose = manipulator.get_current_pose(manipulator.get_end_effector_link()).pose
        print(self.start_pose)

        manipulator.set_goal_tolerance(0.2)
        manipulator.set_named_target("home")
        manipulator.go()
        rospy.sleep(5)
        manipulator.set_end_effector_link("link_4_r")



if __name__ == "__main__":
    MotionPlanner()
